## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux

julia:
  - 1.4

coveralls: true

notifications:
  email: false

script:
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage = true)'
#after_success:
  # push coverage results to Coveralls
 # - julia -e 'cd(Pkg.dir("AdversarialDriving")); Pkg.add("AdversarialDriving"); using AdversarialDriving; Coveralls.submit(Coveralls.process_folder())'
